try:
    print(1/0)
except Exception as err:
    print(err)
